# -*- yaml -*-

before_script:
  - pip install -r requirements_dev.txt

stages: [ test ]

test35:
  stage: test
  image: python:3.5
  script:
    - tox -e py35

test36:
  stage: test
  image: python:3.6
  script:
    - tox -e py36

test37:
  stage: test
  image: python:3.7
  script:
    - tox -e py37
