# -*- yaml -*-

before_script:
  - pip install -q -r requirements_dev.txt

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

stages: [ test, deploy ]

test:3.5:
  stage: test
  image: python:3.5
  script: [ tox -e py35 ]
  coverage: '/^TOTAL.*\s(\d+)%\s*$/'

test:3.6:
  stage: test
  image: python:3.6
  script: [ tox -e py36 ]
  coverage: '/^TOTAL.*\s(\d+)%\s*$/'

test:3.7:
  stage: test
  image: python:3.7
  script: [ tox -e py37 ]
  coverage: '/^TOTAL.*\s(\d+)%\s*$/'

test:build-docs:
  stage: test
  image: python:3.7
  script:
    - pip3 install --upgrade --force-reinstall -e .
    - sphinx-build -W ./docs ./public

pages:
  image: python:3.7
  stage: deploy
  script:
    - pip3 install --upgrade --force-reinstall -e .
    - sphinx-build -W ./docs ./public
  artifacts:
    paths: [ ./public ]
  only: [ master ]
