#!/bin/bash
set -euo pipefail

PROJECT_ROOT=$(readlink -f $(dirname $BASH_SOURCE[0])/../)

export PYTHONPATH=${PROJECT_ROOT}

pip install -U -e ${PROJECT_ROOT}

PYTERRANETES_INSTALL_DIR=$(python -c 'import p10s as _; print(_.__path__[0])')

pytest -vvv "--cov=${PYTERRANETES_INSTALL_DIR}" "$@" ${PROJECT_ROOT}/tests/
coverage html
