# -*- yaml -*-

image: python:3.7

before_script:
  - pip install -q ply
  - pip install -q -r requirements_dev.txt

stages: [ test-python, test-docs, deploy ]

test:py37: &test-python
  stage: test-python
  script: [ tox -e py37 ]
  coverage: '/^TOTAL.*\s(\d+)%\s*$/'

test:py36:
  stage: test-python
  image: python:3.6
  script: [ tox -e py36 ]

test:py35:
  stage: test-python
  image: python:3.5
  script: [ tox -e py35 ]

test:build-docs:
  stage: test-docs
  script:
    - pip install --quiet --upgrade --force-reinstall -e .
    - sphinx-build -W ./docs ./public

pages:
  stage: deploy
  script:
    - pip install --quiet --upgrade --force-reinstall -e .
    - sphinx-build -W ./docs ./public
  artifacts:
    paths: [ ./public ]
  only: [ master ]

pypi:
  stage: deploy
  only: [ master ]
  script:
    - ./cicd/upload

