# -*- yaml -*-

image: python:3.7

stages: [ lint, test-python, test-docs, deploy ]

lint:
  stage: lint
  script:
    - pip install --quiet --requirement requirements_dev.txt
    - ./cicd/lint

test:py37:
  stage: test-python
  script:
    - pip install --quiet --requirement requirements_dev.txt
    - tox -e py37
  coverage: '/^TOTAL.*\s(\d+)%\s*$/'

test:py36:
  stage: test-python
  image: python:3.6
  script:
    - pip install --quiet --requirement requirements_dev.txt
    - tox -e py36

test:py35:
  stage: test-python
  image: python:3.5
  script:
    - pip install --quiet --requirement requirements_dev.txt
    - tox -e py35

test:build-docs:
  stage: test-docs
  script:
    - pip install --quiet sphinx --editable .
    - sphinx-build -W ./docs ./public

pages:
  stage: deploy
  script:
    - pip install --quiet sphinx --editable .
    - sphinx-build -W ./docs ./public
  artifacts:
    paths: [ ./public ]
  only: [ master ]

pypi:
  stage: deploy
  script:
    - ./cicd/upload
  only: [ master ]
