# -*- yaml -*-

image: python:3.7

stages: [ lint, test-python, test-docs, deploy ]

lint:
  stage: lint
  script:
    - pip install --quiet --requirement requirements_dev.txt
    - ./cicd/lint

test:py37:
  stage: test-python
  script:
    - pip install --quiet --requirement requirements_dev.txt
    - tox -e py37
  coverage: '/^TOTAL.*\s(\d+)%\s*$/'

test:py36:
  stage: test-python
  image: python:3.6
  script:
    - pip install --quiet --requirement requirements_dev.txt
    - tox -e py36

test:py35:
  stage: test-python
  image: python:3.5
  script:
    # black doesn't run on pyhotn 3.5, we're not using it for the
    # tests anyway, so this is ok.
    - sed 's/^black$//' -i requirements_dev.txt
    - pip install --quiet --requirement requirements_dev.txt
    - tox -e py35

test:build-docs:
  stage: test-docs
  script: [ ./cicd/build-docs ]

pages:
  stage: deploy
  script: [ ./cicd/build-docs ]
  artifacts:
    paths: [ ./public ]
  only: [ master ]

pypi:
  stage: deploy
  script: [ ./cicd/upload ]
  only: [ master ]
