# -*- yaml -*-

image: python:3.7

stages: [ lint, test-python, test-docs, deploy ]

lint:
  stage: lint
  script:
    - pip install --quiet --requirement requirements_dev.txt
    - ./cicd/lint

test:py36:
  stage: test-python
  image: python:3.6
  script:
    - pip install --quiet --requirement requirements_dev.txt
    - tox -e py36

test:py37:
  stage: test-python
  image: python:3.7
  script:
    - pip install --quiet --requirement requirements_dev.txt
    - tox -e py37
  coverage: '/^TOTAL.*\s(\d+)%\s*$/'

test:py38:
  stage: test-python
  image: python:3.8
  script:
    - pip install --quiet --requirement requirements_dev.txt
    - tox -e py38
  coverage: '/^TOTAL.*\s(\d+)%\s*$/'

test:py39:
  stage: test-python
  image: python:3.9
  script:
    - pip install --quiet --requirement requirements_dev.txt
    - tox -e py39
  coverage: '/^TOTAL.*\s(\d+)%\s*$/'

test:build-docs:
  stage: test-docs
  script: [ ./cicd/build-docs ]

pages:
  stage: deploy
  script: [ ./cicd/build-docs ]
  artifacts:
    paths: [ ./public ]
  only: [ master ]

pypi:
  stage: deploy
  script: [ ./cicd/upload ]
  only: [ master ]
